[tools]
rojo = {github="rojo-rbx/rojo", version="7.2.1"}
selene = {github="Kampfkarren/selene", version="0.24.0"}
StyLua = {github="JohnnyMorganz/StyLua", version="0.16.1"}
rbxcloud = {github="Sleitnick/rbxcloud", version="0.3.0"}