[package]
name = "dev/workflow-scaffold"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.4.7"
roact = "roblox/roact@1.4.4"
redux = "roblox/rodux@3.0.0"
roact-rodux = "roblox/roact-rodux@0.5.1"
cmdr = "evaera/cmdr@1.9.0"
testez = "roblox/testez@0.4.1"